name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container:
      image: dtrussel/embedded-c-cpp-builder:main

    steps:
    - uses: actions/checkout@v3

    - name: Build All
      run: ./build.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mbed-build-artifacts
        path: |
          build/coverage-report/
          doc/build/html

      
